### ISSUE TITLE
the web that is to download VGG-16 pretrained model  does not exist

### ISSUE THREAD

**Issue by Yong-DAI** [VinniaKemala/sketch-inversion#1]
the web that is to download VGG-16 pretrained model  does not exist, could you please update it or email it to me , thank you very much, chd-dy@foxmail.com

sincere regards

**Comment by VinniaKemala** [comment]
Hi @Dr-Daniel-Dai 
I already updated the link on the README.
You can download the model from here: http://data.dmlc.ml/mxnet/models/imagenet/vgg/

**Comment by Yong-DAI** [comment]
thanks a lot, I appreciate this!
